[sinks.influxdb_metrics]
title = "InfluxDB 2 Metrics"
beta = true
common = false
delivery_guarantee = "best_effort"
egress_method = "batching"
function_category = "transmit"
healthcheck = true
input_types = ["metric"]
service_providers = ["InfluxData"]
write_to_description = "[InfluxDB][urls.influxdb] using [HTTP API][urls.influxdb_http_api]"

<%= render("_partials/_component_options.toml", type: "sink", name: "influxdb_metrics") %>

<%= render("_partials/_batch_options.toml", namespace: "sinks.influxdb_metrics.options", common: false, max_events: 20, max_size: nil, timeout_secs: 1) %>

<%= render(
  "_partials/_request_options.toml",
  namespace: "sinks.influxdb_metrics.options",
  common: false,
  in_flight_limit: 5,
  rate_limit_duration_secs: 1,
  rate_limit_num: 5,
  retry_attempts: -1,
  retry_initial_backoff_secs: 1,
  retry_max_duration_secs: 10,
  timeout_secs: 60
) %>

[sinks.influxdb_metrics.options.endpoint]
type = "string"
common = true
examples = ["https://us-west-2-1.aws.cloud2.influxdata.com", "http://influxdb:9999"]
required = true
description = "InfluxDB endpoint to send metrics to."

[sinks.influxdb_metrics.options.org]
type = "string"
common = true
examples = ["Organization", "33f2cff0a28e5b63"]
required = true
description = "Specifies the destination organization for writes."

[sinks.influxdb_metrics.options.bucket]
type = "string"
common = true
examples = ["vector-bucket", "4d2225e4d3d49f75"]
required = true
description = "The destination bucket for writes."

[sinks.influxdb_metrics.options.token]
type = "string"
common = true
examples = ["${INFLUXDB_TOKEN_ENV_VAR}", "ef8d5de700e7989468166c40fc8a0ccd"]
required = true
description = "InfluxDB [authentication token][urls.influxdb_authentication_token]"

[sinks.influxdb_metrics.options.namespace]
type = "string"
common = true
examples = ["service"]
required = true
description = "A prefix that will be added to all metric names."
